name: adidas_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  carousel_pro:
  smooth_star_rating:
  flutter_vector_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
    - family: Ionicons
      fonts:
        - asset: assets/fonts/Ionicons.ttf
    - family: AntDesign
      fonts:
        - asset: assets/fonts/AntDesign.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/fonts/MaterialCommunityIcons.ttf
    - family: SimpleLineIcons
      fonts:
        - asset: assets/fonts/SimpleLineIcons.ttf
   

  assets:
      - assets/home.png
      - assets/view.png
      - assets/cart.png
      - assets/user.png
      - assets/list.png
      - assets/search.png
      - assets/favorite_empty.png
      - assets/adidas_nav.png
      - assets/temp/photo.png
      - assets/temp/man.png
      - assets/temp/9.png
      - assets/temp/product/1.png
      - assets/temp/product/user1.jpg
      - assets/temp/product/user2.png
      - assets/temp/product/user3.png